import { Application, Candidate, Job, Resume } from './types';

export const jobs: Job[] = [
  {
    id: 'job-1',
    orgId: 'org-1',
    roleType: 'Dental Assistant - Surgical',
    clinicName: 'Bluewave Dental',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    specialtyTags: ['4-hand dentistry', 'Implant chairside', 'Sterilization'],
    employmentType: 'Full-time',
    shiftType: 'Day',
    internshipAvailable: false,
    salaryRange: '$2,800 - $3,500',
    benefits: ['Medical', 'CPD allowance', 'Annual bonus'],
    requirements: ['1+ year chairside', 'Comfortable with digital x-rays', 'Infection control certificate'],
    postedAt: '2024-05-12',
    experienceLevel: 'Junior',
    newGradWelcome: true,
    trainingProvided: true,
    description: 'Assist senior dentists in surgical and implant cases, manage chair turnover, and ensure sterilization excellence.'
  },
  {
    id: 'job-2',
    orgId: 'org-1',
    roleType: 'Dental Student Intern',
    clinicName: 'Smile Hub',
    city: 'Singapore',
    country: 'Singapore',
    specialtyTags: ['Intraoral scanning', 'Patient education', 'Charting'],
    employmentType: 'Part-time',
    shiftType: 'Day',
    internshipAvailable: true,
    salaryRange: '$1,200 - $1,600',
    benefits: ['Training', 'Study-friendly schedule'],
    requirements: ['Final year student', 'Strong communication', 'Basic 4-hand support'],
    postedAt: '2024-05-10',
    experienceLevel: 'Student',
    newGradWelcome: true,
    trainingProvided: true,
    description: 'Shadow clinicians, assist with preventive dentistry, and practice scanning workflows.'
  },
  {
    id: 'job-3',
    orgId: 'org-1',
    roleType: 'Dental Nurse - Pediatric',
    clinicName: 'Happy Teeth Kids',
    city: 'Petaling Jaya',
    country: 'Malaysia',
    specialtyTags: ['Tell-show-do', 'Behavior guidance', 'Nitrous support'],
    employmentType: 'Full-time',
    shiftType: 'Day',
    internshipAvailable: false,
    salaryRange: '$3,000 - $3,800',
    benefits: ['Medical', 'CPD allowance', 'Uniforms'],
    requirements: ['2+ years pediatric experience', 'PALS preferred', 'Great with anxious kids'],
    postedAt: '2024-05-08',
    experienceLevel: 'Mid',
    newGradWelcome: false,
    trainingProvided: true,
    description: 'Partner with pediatric dentists to deliver calm and safe visits for children.'
  },
  {
    id: 'job-4',
    orgId: 'org-1',
    roleType: 'Treatment Coordinator',
    clinicName: 'PrimeCare Dental',
    city: 'Johor Bahru',
    country: 'Malaysia',
    specialtyTags: ['Case presentation', 'Financing', 'Aligner programs'],
    employmentType: 'Full-time',
    shiftType: 'Day',
    internshipAvailable: false,
    salaryRange: '$3,200 - $4,200',
    benefits: ['Commission', 'Dental coverage'],
    requirements: ['Sales mindset', 'Understands ortho packages', 'CRM familiarity'],
    postedAt: '2024-05-06',
    experienceLevel: 'Mid',
    newGradWelcome: false,
    trainingProvided: false,
    description: 'Guide patients through ortho and implant treatment plans with empathy and clarity.'
  },
  {
    id: 'job-5',
    orgId: 'org-1',
    roleType: 'Infection Control Lead',
    clinicName: 'SterileSmiles',
    city: 'Singapore',
    country: 'Singapore',
    specialtyTags: ['Sterilization', 'Inventory', 'Audit'],
    employmentType: 'Full-time',
    shiftType: 'Day',
    internshipAvailable: false,
    salaryRange: '$3,500 - $4,500',
    benefits: ['Medical', 'Annual training'],
    requirements: ['Lead CSA experience', 'Understands autoclave validation', 'OSHA/ISO knowledge'],
    postedAt: '2024-05-04',
    experienceLevel: 'Senior',
    newGradWelcome: false,
    trainingProvided: false,
    description: 'Own infection control SOPs, track instruments, and train junior assistants.'
  },
  {
    id: 'job-6',
    orgId: 'org-1',
    roleType: 'Dental Assistant - Endodontics',
    clinicName: 'CanalCare Specialists',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    specialtyTags: ['Microscope setup', 'Rubber dam', 'CBCT basics'],
    employmentType: 'Full-time',
    shiftType: 'Day',
    internshipAvailable: false,
    salaryRange: '$2,900 - $3,600',
    benefits: ['Medical', 'Training allowance'],
    requirements: ['Comfortable with apex locators', 'Understands irrigation workflow'],
    postedAt: '2024-05-02',
    experienceLevel: 'Junior',
    newGradWelcome: true,
    trainingProvided: true,
    description: 'Support endodontists with efficient 4-hand dentistry and aseptic protocols.'
  },
  {
    id: 'job-7',
    orgId: 'org-1',
    roleType: 'Dental Receptionist',
    clinicName: 'City Dental Lounge',
    city: 'George Town',
    country: 'Malaysia',
    specialtyTags: ['Scheduling', 'Insurance claims', 'Customer care'],
    employmentType: 'Full-time',
    shiftType: 'Day',
    internshipAvailable: false,
    salaryRange: '$2,400 - $3,000',
    benefits: ['Medical', 'Dental perks'],
    requirements: ['Front desk experience', 'Understands chairtime allocation', 'POS systems'],
    postedAt: '2024-04-30',
    experienceLevel: 'Junior',
    newGradWelcome: true,
    trainingProvided: true,
    description: 'Be the first smile patients see while keeping the schedule optimized.'
  },
  {
    id: 'job-8',
    orgId: 'org-1',
    roleType: 'Orthodontic Assistant',
    clinicName: 'Align Studio',
    city: 'Singapore',
    country: 'Singapore',
    specialtyTags: ['Aligner tracking', 'Bracket bonding assist', 'Photography'],
    employmentType: 'Full-time',
    shiftType: 'Day',
    internshipAvailable: false,
    salaryRange: '$3,100 - $3,900',
    benefits: ['Medical', 'Quarterly bonus'],
    requirements: ['Understands ortho inventory', 'TAD setup familiarity'],
    postedAt: '2024-04-28',
    experienceLevel: 'Junior',
    newGradWelcome: true,
    trainingProvided: true,
    description: 'Keep ortho days flowing with precise setup and patient education.'
  },
  {
    id: 'job-9',
    orgId: 'org-1',
    roleType: 'Dental Assistant - Oral Surgery',
    clinicName: 'MaxFac Center',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    specialtyTags: ['Surgical tray setup', 'Sedation support', 'Suture removal'],
    employmentType: 'Full-time',
    shiftType: 'Day',
    internshipAvailable: false,
    salaryRange: '$3,200 - $4,000',
    benefits: ['Medical', 'On-call allowance'],
    requirements: ['Surgical assisting experience', 'Understands sterile field'],
    postedAt: '2024-04-25',
    experienceLevel: 'Mid',
    newGradWelcome: false,
    trainingProvided: true,
    description: 'Assist oral surgeons in complex extractions and jaw procedures.'
  },
  {
    id: 'job-10',
    orgId: 'org-1',
    roleType: 'Clinic Manager',
    clinicName: 'Harbor Dental',
    city: 'Johor Bahru',
    country: 'Malaysia',
    specialtyTags: ['Roster planning', 'KPI tracking', 'Supplier management'],
    employmentType: 'Full-time',
    shiftType: 'Day',
    internshipAvailable: false,
    salaryRange: '$4,000 - $5,000',
    benefits: ['Medical', 'Performance bonus'],
    requirements: ['2+ years clinic lead', 'Understands chair utilization', 'Basic HR'],
    postedAt: '2024-04-22',
    experienceLevel: 'Senior',
    newGradWelcome: false,
    trainingProvided: false,
    description: 'Lead a growing clinic with data-driven scheduling and people-first leadership.'
  },
  {
    id: 'job-11',
    orgId: 'org-1',
    roleType: 'Dental Technologist (Digital)',
    clinicName: 'SmileLab',
    city: 'Singapore',
    country: 'Singapore',
    specialtyTags: ['3D printing', 'Model trimming', 'CAD/CAM'],
    employmentType: 'Full-time',
    shiftType: 'Day',
    internshipAvailable: false,
    salaryRange: '$3,800 - $4,800',
    benefits: ['Medical', 'Learning stipend'],
    requirements: ['Exocad or 3Shape basics', 'Understands occlusion concepts'],
    postedAt: '2024-04-20',
    experienceLevel: 'Mid',
    newGradWelcome: true,
    trainingProvided: true,
    description: 'Bridge chairside scanning to lab production with digital workflows.'
  },
  {
    id: 'job-12',
    orgId: 'org-1',
    roleType: 'Sterilization Tech (Evenings)',
    clinicName: 'NightGuard Dental',
    city: 'Petaling Jaya',
    country: 'Malaysia',
    specialtyTags: ['Autoclave', 'Inventory', 'Turnover'],
    employmentType: 'Part-time',
    shiftType: 'Night',
    internshipAvailable: true,
    salaryRange: '$1,800 - $2,400',
    benefits: ['Flexible shifts'],
    requirements: ['Understands cassettes/bags', 'Detail oriented'],
    postedAt: '2024-04-18',
    experienceLevel: 'Junior',
    newGradWelcome: true,
    trainingProvided: true,
    description: 'Own evening sterilization and restock for next-day readiness.'
  },
  {
    id: 'job-13',
    orgId: 'org-1',
    roleType: 'Dental Assistant - Prostho',
    clinicName: 'ReLine Prosthodontics',
    city: 'Singapore',
    country: 'Singapore',
    specialtyTags: ['Impression taking', 'Facebow', 'Bite registration'],
    employmentType: 'Full-time',
    shiftType: 'Day',
    internshipAvailable: false,
    salaryRange: '$3,200 - $4,000',
    benefits: ['Medical', 'Lab collaboration'],
    requirements: ['Understands denture steps', 'Chairside temp fabrication'],
    postedAt: '2024-04-15',
    experienceLevel: 'Mid',
    newGradWelcome: true,
    trainingProvided: true,
    description: 'Support complex prostho cases and coordinate with partner labs.'
  },
  {
    id: 'job-14',
    orgId: 'org-1',
    roleType: 'Dental Assistant - Hygiene',
    clinicName: 'Fresh Breath Dental',
    city: 'George Town',
    country: 'Malaysia',
    specialtyTags: ['Airflow', 'Sealants', 'Oral hygiene coaching'],
    employmentType: 'Part-time',
    shiftType: 'Day',
    internshipAvailable: false,
    salaryRange: '$2,600 - $3,200',
    benefits: ['Medical', 'CPD budget'],
    requirements: ['Understands perio charting', 'Gentle patient handling'],
    postedAt: '2024-04-12',
    experienceLevel: 'Junior',
    newGradWelcome: true,
    trainingProvided: true,
    description: 'Partner with hygienists to deliver preventive care days.'
  },
  {
    id: 'job-15',
    orgId: 'org-1',
    roleType: 'Dental Assistant - Implant Coordinator',
    clinicName: 'Osseo Dental',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    specialtyTags: ['Implant kit prep', 'Surgical guide handling', 'Prosth tracking'],
    employmentType: 'Full-time',
    shiftType: 'Day',
    internshipAvailable: false,
    salaryRange: '$3,500 - $4,300',
    benefits: ['Medical', 'Implant training'],
    requirements: ['Understands implant timelines', 'CBCT basics'],
    postedAt: '2024-04-10',
    experienceLevel: 'Mid',
    newGradWelcome: false,
    trainingProvided: true,
    description: 'Own implant day readiness and follow-through on restorations.'
  },
  {
    id: 'job-16',
    orgId: 'org-1',
    roleType: 'Dental Assistant - Sedation',
    clinicName: 'Calm Dental',
    city: 'Singapore',
    country: 'Singapore',
    specialtyTags: ['IV sedation support', 'Vitals monitoring', 'Recovery'],
    employmentType: 'Full-time',
    shiftType: 'Day',
    internshipAvailable: false,
    salaryRange: '$3,400 - $4,200',
    benefits: ['Medical', 'Allowance'],
    requirements: ['BLS/ACLS', 'Understands airway setup'],
    postedAt: '2024-04-08',
    experienceLevel: 'Mid',
    newGradWelcome: false,
    trainingProvided: true,
    description: 'Support IV sedation days with safe monitoring and calm reassurance.'
  },
  {
    id: 'job-17',
    orgId: 'org-1',
    roleType: 'Dental Assistant - General',
    clinicName: 'Neighborhood Smiles',
    city: 'Melaka',
    country: 'Malaysia',
    specialtyTags: ['4-hand dentistry', 'Chairside charting', 'Patient education'],
    employmentType: 'Full-time',
    shiftType: 'Day',
    internshipAvailable: false,
    salaryRange: '$2,700 - $3,300',
    benefits: ['Medical', 'Team meals'],
    requirements: ['Friendly communicator', 'Understands restorative setup'],
    postedAt: '2024-04-05',
    experienceLevel: 'Junior',
    newGradWelcome: true,
    trainingProvided: true,
    description: 'General chairside role across restorative, perio, and preventive days.'
  },
  {
    id: 'job-18',
    orgId: 'org-1',
    roleType: 'Dental Assistant - Scanner',
    clinicName: 'Scan+Smile',
    city: 'Singapore',
    country: 'Singapore',
    specialtyTags: ['Intraoral scanning', 'Bite scan', 'Digital workflow'],
    employmentType: 'Contract',
    shiftType: 'Rotating',
    internshipAvailable: false,
    salaryRange: '$2,800 - $3,400',
    benefits: ['Tech training'],
    requirements: ['IOS scanner proficiency', 'Understands margin capture'],
    postedAt: '2024-04-02',
    experienceLevel: 'Junior',
    newGradWelcome: true,
    trainingProvided: true,
    description: 'Float between clinics to capture clean digital scans for labs.'
  },
  {
    id: 'job-19',
    orgId: 'org-1',
    roleType: 'Dental Assistant - Endo/Prosth Float',
    clinicName: 'Canal & Crown',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    specialtyTags: ['Rubber dam', 'Shade selection', 'CBCT basics'],
    employmentType: 'Full-time',
    shiftType: 'Day',
    internshipAvailable: false,
    salaryRange: '$3,000 - $3,800',
    benefits: ['Medical', 'Training'],
    requirements: ['Strong organization', 'Understands lab slips'],
    postedAt: '2024-03-30',
    experienceLevel: 'Junior',
    newGradWelcome: true,
    trainingProvided: true,
    description: 'Split time assisting endodontist and prosthodontist with smooth turnover.'
  },
  {
    id: 'job-20',
    orgId: 'org-1',
    roleType: 'Dental Assistant - Steri & Floater',
    clinicName: 'NorthStar Dental',
    city: 'Singapore',
    country: 'Singapore',
    specialtyTags: ['Sterilization', 'Chair turnover', 'Inventory'],
    employmentType: 'Full-time',
    shiftType: 'Rotating',
    internshipAvailable: true,
    salaryRange: '$2,600 - $3,200',
    benefits: ['Medical', 'Uniforms'],
    requirements: ['Detail-focused', 'Understands cassette flow'],
    postedAt: '2024-03-28',
    experienceLevel: 'Student',
    newGradWelcome: true,
    trainingProvided: true,
    description: 'Keep ops flowing with timely turnover and sterile processing.'
  }
];

export const candidates: Candidate[] = [
  {
    id: 'cand-1',
    name: 'Amira Rahman',
    school: 'Mahsa University',
    gradDate: '2024-09-01',
    skills: ['4-hand dentistry', 'Rubber dam', 'Intraoral scanning'],
    status: 'Applied',
    rating: 4.5,
    city: 'Kuala Lumpur',
    notes: 'Strong restorative exposure',
    interestedIn: 'General assistant',
    jobId: 'job-1',
    jobTitle: 'Dental Assistant - Surgical'
  },
  {
    id: 'cand-2',
    name: 'Darren Lim',
    school: 'IMU',
    gradDate: '2023-12-01',
    skills: ['Sterilization', 'Inventory', 'Autoclave'],
    status: 'Shortlisted',
    rating: 4.2,
    city: 'Petaling Jaya',
    notes: 'Takes initiative on turnover',
    interestedIn: 'Infection control',
    jobId: 'job-5',
    jobTitle: 'Infection Control Lead'
  },
  {
    id: 'cand-3',
    name: 'Sofia Tan',
    school: 'NUS Dentistry',
    gradDate: '2024-06-01',
    skills: ['Intraoral scanning', 'Aligner tracking', 'Photography'],
    status: 'Interview',
    rating: 4.7,
    city: 'Singapore',
    interestedIn: 'Ortho assistant',
    jobId: 'job-8',
    jobTitle: 'Orthodontic Assistant'
  },
  {
    id: 'cand-4',
    name: 'Hafiz Abdullah',
    school: 'AIMST University',
    gradDate: '2025-01-01',
    skills: ['Chairside charting', 'Patient education', 'Sealants'],
    status: 'Offer',
    rating: 4.0,
    city: 'Johor Bahru',
    interestedIn: 'Hygiene support',
    jobId: 'job-14',
    jobTitle: 'Dental Assistant - Hygiene'
  },
  {
    id: 'cand-5',
    name: 'Rachel Ong',
    school: 'NYU College of Dentistry',
    gradDate: '2022-05-01',
    skills: ['Microscope setup', 'Rubber dam', 'CBCT basics'],
    status: 'Hired',
    rating: 4.8,
    city: 'Singapore',
    notes: 'Specializes in endo support',
    jobId: 'job-6',
    jobTitle: 'Dental Assistant - Endodontics'
  },
  {
    id: 'cand-6',
    name: 'Joshua Lee',
    school: "Taylor's University",
    gradDate: '2023-08-01',
    skills: ['Chair turnover', 'Autoclave', 'Inventory'],
    status: 'Rejected',
    rating: 3.8,
    city: 'Melaka',
    notes: 'Good attitude, needs more scanning practice',
    jobId: 'job-17',
    jobTitle: 'Dental Assistant - General'
  },
  {
    id: 'cand-7',
    name: 'Nurul Izzah',
    school: 'UiTM',
    gradDate: '2024-11-01',
    skills: ['Tell-show-do', 'Behavior guidance', 'Nitrous support'],
    status: 'Applied',
    rating: 4.3,
    city: 'Kuala Lumpur',
    interestedIn: 'Pediatric assistant',
    jobId: 'job-3',
    jobTitle: 'Dental Nurse - Pediatric'
  },
  {
    id: 'cand-8',
    name: 'Kevin Chan',
    school: 'Nanyang Polytechnic',
    gradDate: '2023-04-01',
    skills: ['Case presentation', 'CRM', 'Financing'],
    status: 'Shortlisted',
    rating: 4.1,
    city: 'Singapore',
    interestedIn: 'Treatment coordinator',
    jobId: 'job-4',
    jobTitle: 'Treatment Coordinator'
  },
  {
    id: 'cand-9',
    name: 'Liyana Mohd',
    school: 'Mahsa University',
    gradDate: '2024-02-01',
    skills: ['Sterilization', 'Sealants', 'Intraoral scanning'],
    status: 'Interview',
    rating: 4.4,
    city: 'Petaling Jaya',
    jobId: 'job-1',
    jobTitle: 'Dental Assistant - Surgical'
  },
  {
    id: 'cand-10',
    name: 'Marcus Teh',
    school: 'IMU',
    gradDate: '2022-11-01',
    skills: ['3D printing', 'Model trimming', 'CAD/CAM'],
    status: 'Offer',
    rating: 4.6,
    city: 'Kuala Lumpur',
    interestedIn: 'Digital lab',
    jobId: 'job-11',
    jobTitle: 'Dental Technologist (Digital)'
  },
  {
    id: 'cand-11',
    name: 'Aisha Karim',
    school: 'UiTM',
    gradDate: '2023-09-01',
    skills: ['Vitals monitoring', 'IV support', 'Recovery'],
    status: 'Applied',
    rating: 4.2,
    city: 'Singapore',
    interestedIn: 'Sedation support',
    jobId: 'job-16',
    jobTitle: 'Dental Assistant - Sedation'
  },
  {
    id: 'cand-12',
    name: 'Bryan Yeoh',
    school: 'Mahsa University',
    gradDate: '2025-03-01',
    skills: ['Chairside charting', 'Patient education'],
    status: 'Rejected',
    rating: 3.5,
    city: 'Johor Bahru',
    jobId: 'job-7',
    jobTitle: 'Dental Receptionist'
  }
];

export const applications: Application[] = [
  { id: 'app-1', jobId: 'job-1', status: 'Applied', appliedAt: '2024-05-12', candidateName: 'Amira Rahman', orgId: 'org-1' },
  { id: 'app-2', jobId: 'job-8', status: 'Shortlisted', appliedAt: '2024-05-10', candidateName: 'Sofia Tan', orgId: 'org-1' },
  { id: 'app-3', jobId: 'job-6', status: 'Interview', appliedAt: '2024-05-08', candidateName: 'Liyana Mohd', orgId: 'org-1' },
  { id: 'app-4', jobId: 'job-3', status: 'Rejected', appliedAt: '2024-05-07', candidateName: 'Joshua Lee', orgId: 'org-1' },
  { id: 'app-5', jobId: 'job-2', status: 'Offer', appliedAt: '2024-05-05', candidateName: 'Darren Lim', orgId: 'org-1' }
];

export const resumes: Resume[] = [
  { id: 'res-1', name: 'Amira_Rahman_CV.pdf', uploadedAt: '2024-05-01', category: 'Resume' },
  { id: 'res-2', name: 'Clinical_Scans_Portfolio.pdf', uploadedAt: '2024-04-20', category: 'Portfolio' },
  { id: 'res-3', name: 'Dental_Assistant_Profile.docx', uploadedAt: '2024-03-18', category: 'Resume' }
];
